version: "3.0"

services:

  db:
    build: ./aupoBookStoreBackEnd/db-docker
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "hard_pwd"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root ", "-phard_pwd"]
      timeout: 1s
      retries: 50

  app:
    build: ./aupoBookStoreBackEnd
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  
  front:
    build: ./aupoBookStroreFrontEnd
    ports:
      - "80:80"